openapi: '3.0.0'
info:
  description: This is the API documentation for the COP 4331 Small Project
  version: 1.0.0
  title: The Small Project
  contact:
    email: lo658201+smprojAPI@ucf.edu
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  
servers:
  - url: http://167.99.125.237/LAMPAPI
    description: Optional server description, e.g. Main (production) server


paths:
  /Login.php:
    post:
      tags:
      - Users
      summary: Logs in to the Application
      operationId: attemptLogin # No idea what this section does
      description: Logs in to the Application
      requestBody:
        description: "Error Status Codes\n-1: Invalid User/Password combination\n0<ID: Success"
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/Login_In'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Login_Out"
        404:
          description: URL Not Found
        500:
          description: Server Error
  /SignUp.php:
    post:
      tags:
      - SignUp
      summary: Registers a User on the Application
      operationId: attemptSignUp # No idea what this section does
      description: Registers a User on the Application app database
      requestBody:
        description: "Error Status Codes\n-1: Password does not match\n-2: Username already exists\n-3: Please fill in missing boxes\n-4: Username and password cannot contain spaces\n0<ID: Success"
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUp_In'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignUp_Out"
        404:
          description: URL Not Found
        500:
          description: Server Error
  /Contacts.php:
    post:
      tags:
      - Contacts
      summary: Contact Operations
      operationId: contactsID # No idea what this section does
      description: Controls all contact operations.
      requestBody:
        description: "Error Status Codes\n-12: Row does not exist\n-13: Access Denied. Invalid UserID Authentification\n0<ID: Success"
        content:
          application/json:
            schema:
              anyOf:
                [
                  $ref: "#/components/schemas/Contacts_Edit_In",
                  $ref: "#/components/schemas/Contacts_SaveEdit_In",
                  $ref: "#/components/schemas/Contacts_Delete_In",
                  $ref: "#/components/schemas/Contacts_Add_In",
                  $ref: "#/components/schemas/Contacts_Search_In"
                ]
            examples:
              example1: 
                $ref: "#/components/examples/Contacts_Edit_In"
              example2:
                $ref: "#/components/examples/Contacts_SaveEdit_In"
              example3: 
                $ref: "#/components/examples/Contacts_Delete_In"
              example4: 
                $ref: "#/components/examples/Contacts_Add_In"
              example5: 
                $ref: "#/components/examples/Contacts_Search_In"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                anyOf:
                  [
                    $ref: "#/components/schemas/Contacts_Edit_Out",
                    $ref: "#/components/schemas/Contacts_SaveEdit_Out",
                    $ref: "#/components/schemas/Contacts_Delete_Out",
                    $ref: "#/components/schemas/Contacts_Add_Out",
                    $ref: "#/components/schemas/Contacts_Search_Out"
                  ]
              examples:
                example1: 
                  $ref: "#/components/examples/Contacts_Edit_Out"
                example2: 
                  $ref: "#/components/examples/Contacts_SaveEdit_Out"
                example3: 
                  $ref: "#/components/examples/Contacts_Delete_Out"
                example4: 
                  $ref: "#/components/examples/Contacts_Add_Out"
                example5: 
                  $ref: "#/components/examples/Contacts_Search_Out"
        404:
          description: URL Not Found
        500:
          description: Server Error
          
components:
  schemas:
    Login_In:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: "BobBuildsBridges"
          description: "The User's username"
        password:
          type: string
          example: "secret2148"
          description: "The User's password"
    Login_Out:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          example: 574231
          description: "The active User's id"
        name:
          type: string
          example: "Bob the Builder"
          description: "The User's name"
        error:
          type: string
          example: ""
          description: "An error string"
    SignUp_In:
      type: object
      required:
      - username
      - password
      - confirmPass
      - name
      properties:
        username:
          type: string
          example: "BobBuildsBridges"
          description: "The User's username"
        password:
          type: string
          example: "secret2148"
          description: "The User's password"
        confirmPass:
          type: string
          example: "secret2148"
          description: "The User's (confirmed) password"
        name:
          type: string
          example: "Bob the Builder"
          description: "The User's name"
    SignUp_Out:
      type: object
      required:
      - id
      - name
      properties:
        id:
          type: integer
          example: 574231
          description: "The active User's id"
        name:
          type: string
          example: "Bob the Builder"
          description: "The User's name"
        error:
          type: string
          example: ""
          description: "An error string"
    Contacts_Edit_In:
      type: object
      required:
      - mode
      - contactID
      - userID
      properties:
        mode:
          type: integer
          example: 0
          description: "The designated Contacts Operation to run"
        contactID:
          type: integer
          example: 193383
          description: "The Contact-Row to edit"
        userID:
          type: integer
          example: 574231
          description: "The active User's id"
    Contacts_Edit_Out:
      type: object
      required:
      - contactID
      - FirstName
      - LastName
      - Phone
      - Email
      properties:
        contactID:
          type: integer
          example: 193383
          description: "The Contact-Row to edit"
        FirstName:
          type: string
          example: "Tanner"
          description: "The Contact's first name"
        LastName:
          type: string
          example: "Lerun"
          description: "The Contact's last name"
        Email:
          type: string
          example: "tannerLe@hotmail.com"
          description: "The Contact's email"
        Phone:
          type: integer
          example: 1112222333
          description: "The Contact's phone number"
    Contacts_SaveEdit_In:
      type: object
      required:
      - mode
      - InputFirstName
      - InputLastName
      - InputEmail
      - InputPhone
      - contactID
      - userID
      properties:
        mode:
          type: integer
          example: 0
          description: "The designated Contacts Operation to run"
        InputFirstName:
          type: string
          example: "Tanner"
          description: "The Contact's first name"
        InputLastName:
          type: string
          example: "Lerun"
          description: "The Contact's last name"
        InputEmail:
          type: string
          example: "tannerLe@hotmail.com"
          description: "The Contact's email"
        InputPhone:
          type: string
          example: 1112222333
          description: "The Contact's phone number"
        contactID:
          type: integer
          example: 193383
          description: "The Contact-Row the Contact Data is for"
        userID:
          type: integer
          example: 574231
          description: "The active User's id"
    Contacts_SaveEdit_Out:
      type: object
      required:
      - id
      properties:
        id:
          type: integer
          example: 0
          description: "An error code"
        error:
          type: string
          example: ""
          description: "An error string"
    Contacts_Delete_In:
      type: object
      required:
      - mode
      - InputID
      - id
      properties:
        mode:
          type: integer
          example: 4
          description: "The designated Contacts Operation to run"
        InputID:
          type: integer
          example: 193383
          description: "The Contact-Row to operate upon"
        id:
          type: integer
          example: 574231
          description: "The active User's id"
    Contacts_Delete_Out:
      type: object
      required:
      - id
      properties:
        id:
          type: integer
          example: 574231
          description: "The active User's id"
        error:
          type: string
          example: ""
          description: "An error string"
    Contacts_Add_In:
      type: object
      required:
      - mode
      - InputFirstName
      - InputLastName
      - InputEmail
      - InputPhone
      - id
      properties:
        mode:
          type: integer
          example: 5
          description: "The Contact-Row the Contact Data is for"
        InputFirstName: 
          type: string
          example: "Tanner"
          description: "The Contact's first name"
        InputLastName:
          type: string
          example: "Lerun"
          description: "The Contact's last name"
        InputEmail:
          type: string
          example: "tannerLe@hotmail.com"
          description: "The Contact's email"
        InputPhone:
          type: integer
          example: 1112222333
          description: "The Contact's phone number"
        id:
          type: integer
          example: 574231
          description: "The active User's id"
    Contacts_Add_Out:
      type: object
      required:
      - id
      properties:
        id:
          type: integer
          example: 193383
          description: "The number of the row that got added to Contacts"
        error:
          type: string
          example: ""
          description: "An error string"
    Contacts_Search_In:
      type: object
      required:
      - mode
      - id
      - searchTerm
      properties:
        mode:
          type: integer
          example: 6
          description: "The designated Contacts Operation to run"
        id:
          type: integer
          example: 574231
          description: "The active User's id"
        searchterm: 
          type: string
          example: "Tan"
          description: "The term to search for in the database"
    Contacts_Search_Out:
      type: object
      required: 
      - error
      - searchResults
      properties:
        error:
          type: string
          example: ""
          description: "An error string"
        searchResults:
          type: array
          items:
            type: array
            items:
              type: string
          example: [[
            193383,
            "Tanner",
            "Lerun",
            1112222333,
            "tannerLe@hotmail.com",
            574231
          ],
          [
            182738,
            "Tanis",
            "Malron",
            8885555333,
            "malwTa@yahoo.com",
            574231
          ]]
          description: "The search results returned"
  examples:
    Contacts_Add_In:
      summary: "Add Contact Operation"
      value:
        mode: 5
        InputFirstName: "Tanner"
        InputLastName: "Lerun"
        InputEmail: "tannerLe@hotmail.com"
        InputPhone: 1112222333
        id: 574231
    Contacts_Edit_In:
      summary: "Edit Contact Operation"
      value:
        mode: 0
        userID: 574231
        contactID: 193383
    Contacts_SaveEdit_In:
      summary: "SaveEdit Contact Operation"
      value:
        mode: 0
        userID: 574231
        contactID: 193383
        InputFirstName: "Tanner"
        InputLastName: "Lerun"
        InputPhone: 1112222333
        InputEmail: "tannerLe@hotmail.com"
    Contacts_Delete_In:
      summary: "Delete Contact Operation"
      value:
        mode: 4
        id: 574231
        InputID: 193383
    Contacts_Search_In:
      summary: "Search Contact Operation"
      value:
        mode: 6
        id: 574231
        searchTerm: "Tan"
    Contacts_Add_Out:
      summary: "Add Contact Operation"
      value:
        id: -11
        error: "Enter Phone Numbers with ONLY Integer Values."
    Contacts_Edit_Out:
      summary: "Edit Contact Operation"
      value:
        contactID: 193383
        FirstName: "Tanner"
        LastName: "Lerun"
        Phone: 1112222333
        Email: "tannerLe@hotmail.com"
    Contacts_SaveEdit_Out:
      summary: "SaveEdit Contact Operation"
      value:
        id: -7
        error: "Emails cannot contain spaces or aliases"
        
    Contacts_Delete_Out:
      summary: "Delete Contact Operation"
      value:
        id: 574231
        error: ""
    Contacts_Search_Out:
      summary: "Search Contact Operation"
      value:
        error: ""
        searchResults: [[
            193383,
            "Tanner",
            "Lerun",
            1112222333,
            "tannerLe@hotmail.com",
            574231
          ],
          [
            182738,
            "Tanis",
            "Malron",
            8885555333,
            "malwTa@yahoo.com",
            574231
          ]]
